#!/usr/bin/env python
import sys
import hashlib


if len(sys.argv) < 2:
	print '[*] Try -h to get help ...'
else:
	if (sys.argv[1]=='-h'):
		print '[*] -h: to get help\n'+'[*] -f: to get a md5 file---  cmd5 -f source.txt target.txt\n'+'[*] -c: to md5 a string--- cmd5 -c string'
	else:
		m=hashlib.md5() 
		if (sys.argv[1]=='-c' and len(sys.argv)==3):
			m.update(sys.argv[2])
			excodeStr=m.hexdigest()
			print '[*] The result  is: '+excodeStr
		else:
			if (sys.argv[1]=='-f' and len(sys.argv)==4):
				try:
					f=open(sys.argv[2])
					ft=open(sys.argv[3],'w')
					for i in f.readlines():
						i=i.replace('\n','')
						#print i
						m.update(i)
						excodeStr=m.hexdigest()
						ft.write(excodeStr+'\t'+i+'\n')
					ft.close()
					f.close()
				except:
					print "[*] Somethings wrong, maybe the file doesn't exit ..."
			else:
				print '[*] Wrong options, try -h ...'